# ----------------------------------------------------------------------------------------

# Version: 1.0.0
# Created by Guacamoleboy
# Last updated 17/08-2026

# ----------------------------------------------------------------------------------------

version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"