# -------------------------------------------------------------------------------------------------------

# DEVELOPMENT Dockerfile

# Version 1.0.0
# Created by Guacamoleboy
# Last updated: 17/08-2026

# FILE PURPOSE
#   - Sets the development environment

# -------------------------------------------------------------------------------------------------------

FROM node:22-alpine

WORKDIR /workspace

RUN apk add --no-cache \
    git \
    bash

CMD ["sleep", "infinity"]